spring:
  application:
    name: loja-veiculos
  datasource:
    url: jdbc:postgresql://localhost:5432/loja
    password: secret
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    academy.devdojo: debug
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

  threads:
    virtual:
      enabled: true

